### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by SandiHadyono** [ericlie/Laravel-Simple-Todo-List#1]
No application encryption key has been specified. It happen when i run the localhost:8000, before that i got sum error on PackageManifest.php but i can fix it with stackoverflow but the No application encryption key has been specified. i got no idea 

![image](https://user-images.githubusercontent.com/75458624/141890708-4b8c06cb-4929-48f8-bf0d-c12434824988.png)

**Comment by ericlie** [comment]
> No application encryption key has been specified

Thanks for your feedback! When getting started with new laravel project, it is advised to do `php artisan key:generate`
you may also find more information with regards to this issue here at stackoverflow https://stackoverflow.com/questions/44839648/no-application-encryption-key-has-been-specified

Hope this helps

Regards,
